name: Build and deploy container app to Azure Web App - msvc-chat

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Log in to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55
      - name: Build and push image
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-msvc-chat:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@3f1742a3b209ebd19d82b914f43fe1d6b919e536
      with:
        app-name: 'msvc-chat'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_70c064f78e8745a1807ad28c9d6ae16f }}
        images: "${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-msvc-chat:latest"